# Generated by Django 3.0.3 on 2020-03-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200306_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
